### ISSUE TITLE
Infinite Loop for get_random_neighbor() for pcs with conditionals?

### ISSUE THREAD

**Issue by mlindauer** [automl/HPOlibConfigSpace#17]
Hi,

after waiting for more than 30 seconds, I don't get a random_neighbor where the pcs has conditionals, e.g., /data/aad/aclib/target_algorithms/sat/spear-python/spear-params-mixed.pcs

(refactor branch)

Best,
Marius

**Comment by mfeurer** [comment]
Could not reproduce the issue together with Marius.
